name: bull_fs
publish_to: none
description: "Unified file system APIs for user-selected directories."
version: 0.0.1
homepage: https://github.com/flutter-cavalry/bull_fs

environment:
  sdk: ">=3.9.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.18.0
  darwin_url: ^0.6.0
  fast_immutable_collections: ^11.0.0
  flutter:
    sdk: flutter
  io: ^1.0.4
  mime: ">=1.0.4 <3.0.0"
  ns_file_coordinator_util: ^0.25.0
  path: ^1.8.3
  saf_stream: ^0.12.1
  tmp_path: ^1.3.1
  accessing_security_scoped_resource: ^3.2.0
  saf_util: ^0.11.0
  convert: ^3.1.1
  media_mime: ^1.4.0
  meta: ^1.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mgenware_dart_lints: ^8.0.0
