name: bull_fs
publish_to: none
description: "A new Flutter package project."
version: 0.0.1
homepage: https://github.com/mgenware/bull_fs

environment:
  sdk: ">=3.2.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.18.0
  darwin_url: ^0.5.0
  fast_immutable_collections: ^10.0.0
  flutter:
    sdk: flutter
  io: ^1.0.4
  mime: ^2.0.0
  ns_file_coordinator_util:
    git:
      url: https://github.com/flutter-cavalry/ns_file_coordinator_util.git
  path: ^1.8.3
  saf_stream: ^0.9.0
  tmp_path: ^1.3.1
  accessing_security_scoped_resource: ^2.0.0
  saf_util:
    git:
      url: https://github.com/flutter-cavalry/saf_util.git
  convert: ^3.1.1
  media_mime: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mgenware_dart_lints: ^7.0.0
