name: bull_fs
publish_to: none
description: "A new Flutter package project."
version: 0.0.1
homepage: https://github.com/mgenware/bull_fs

environment:
  sdk: ">=3.2.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.18.0
  darwin_url: ^0.5.0
  fast_immutable_collections: ^10.0.0
  flutter:
    sdk: flutter
  io: ^1.0.4
  mime: ^2.0.0
  ns_file_coordinator_util:
    git:
      url: https://github.com/flutter-cavalry/ns_file_coordinator_util.git
  path: ^1.8.3
  saf_stream: ^0.8.0
  tmp_path: ^1.3.1
  accessing_security_scoped_resource: ^2.0.0
  mg_shared_storage: ^0.9.1
  convert: ^3.1.1
  media_mime: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mgenware_dart_lints: ^7.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
